(function(){
const root=document.getElementById('bilal-preview')||document;
const header=root.querySelector('header');if(!header)return;
const slides=[...root.querySelectorAll('.swiper-slide')];
slides.forEach(slide=>{const title=slide.querySelector('h1');const text=title.textContent;title.setAttribute('aria-label',text);title.textContent='';[...text].forEach((letter,i)=>{const span=document.createElement('span');span.className='letter';span.textContent=letter===' '?'\u00a0':letter;span.style.setProperty('--letter-index',i);span.setAttribute('aria-hidden','true');title.append(span)});const rule=document.createElement('div');rule.className='cinema-rule';rule.setAttribute('aria-hidden','true');title.after(rule)});
const sweep=document.createElement('div');sweep.className='cinema-sweep';sweep.setAttribute('aria-hidden','true');header.append(sweep);
const dust=document.createElement('div');dust.className='cinema-dust';dust.setAttribute('aria-hidden','true');for(let i=0;i<24;i++){const dot=document.createElement('i');dot.style.left=`${(i*37)%100}%`;dot.style.top=`${20+(i*19)%75}%`;dot.style.setProperty('--duration',`${8+i%7}s`);dot.style.setProperty('--delay',`${-i*.8}s`);dust.append(dot)}header.append(dust);
const caption=document.createElement('div');caption.className='cinema-caption';caption.textContent='Oumid Bilal · Portfolio';header.append(caption);
const counter=document.createElement('div');counter.className='cinema-counter';counter.innerHTML='<strong>01</strong><span>/ 03</span>';header.append(counter);
function change(){const n=slides.findIndex(s=>s.classList.contains('current'));counter.querySelector('strong').textContent=String(n+1).padStart(2,'0');sweep.classList.remove('play');requestAnimationFrame(()=>requestAnimationFrame(()=>sweep.classList.add('play')))}
new MutationObserver(change).observe(root.querySelector('.swiper-wrapper'),{subtree:true,attributes:true,attributeFilter:['class']});change();
const names=['Snake Game','Pac-Man','Shadow Rush','SeniorConnect'],types=['C++ / SFML','JAVA / SWING','GODOT / 2D','PHP / WEB'];root.querySelectorAll('.gallery>a,.project-item').forEach((card,i)=>{const label=document.createElement('div');label.className='project-motion-label';label.innerHTML=`<strong>${names[i]}</strong><small>${types[i]}</small>`;card.append(label);card.addEventListener('pointermove',e=>{const b=card.getBoundingClientRect();card.style.setProperty('--spot-x',`${(e.clientX-b.left)/b.width*100}%`);card.style.setProperty('--spot-y',`${(e.clientY-b.top)/b.height*100}%`)});});
if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&matchMedia('(hover:hover)').matches){header.addEventListener('pointermove',e=>{const b=header.getBoundingClientRect(),x=((e.clientX-b.left)/b.width-.5),y=((e.clientY-b.top)/b.height-.5);header.style.setProperty('--scene-x',`${x*12}px`);header.style.setProperty('--scene-y',`${y*12}px`);header.style.setProperty('--title-x',`${-x*10}px`);header.style.setProperty('--title-y',`${-y*10}px`)});header.addEventListener('pointerleave',()=>['--scene-x','--scene-y','--title-x','--title-y'].forEach(p=>header.style.setProperty(p,'0px')))}
})();
